CREATE DATABASE OnlineStore;

USE OnlineStore;

CREATE TABLE Cities
(CityID INT
 PRIMARY KEY IDENTITY, 
 [Name] VARCHAR(50) NOT NULL
);

CREATE TABLE Customers
(CustomerID INT
 PRIMARY KEY IDENTITY, 
 [Name]     VARCHAR(50) NOT NULL, 
 Birthdate  DATE, 
 CityID     INT NOT NULL
                CONSTRAINT FK_Customers_CityID FOREIGN KEY REFERENCES Cities(CityID)
);

CREATE TABLE Orders
(OrderID    INT
 PRIMARY KEY IDENTITY, 
 CustomerID INT NOT NULL
                CONSTRAINT FK_Orders_CustomerID FOREIGN KEY REFERENCES Customers(CustomerID)
);

CREATE TABLE ItemTypes
(ItemTypeID INT
 PRIMARY KEY IDENTITY, 
 [Name]     VARCHAR(50) NOT NULL
);

CREATE TABLE Items
(ItemID     INT
 PRIMARY KEY IDENTITY, 
 [Name]     VARCHAR(50) NOT NULL, 
 ItemTypeID INT NOT NULL
                CONSTRAINT FK_Items_ItemTypeID FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
);

CREATE TABLE OrderItems
(OrderID INT NOT NULL
             FOREIGN KEY REFERENCES Orders(OrderID), 
 ItemID  INT NOT NULL
             FOREIGN KEY REFERENCES Items(ItemID)
             CONSTRAINT PK_CompositeOrderIDItemID PRIMARY KEY(OrderID, ItemID)
);